version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    ports:
      - "8080:8080"
      
  flask2:
    build: ./flask2
    container_name: flask2
    restart: always
    environment:
      - APP_NAME=MyFlaskApp2
    expose: 
        - 8081
    ports: 
        - "8081:8081"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "81:81"
    depends_on: 
        - flask
        - flask2